import { z } from "zod";

export const QUALITIES = [
  "Adaptable",
  "Agile",
  "Analytical",
  "Assertive",
  "Brave",
  "Confident",
  "Creative",
  "Focused",
  "Hardworking",
  "Ingenious",
  "Innovative",
  "Intelligent",
  "Kind",
  "Logical",
  "Optimistic",
  "Persistent",
  "Pretty",
  "Reliable",
  "Resourceful",
  "Smart",
  "Strong",
  "Tall",
  "Visionary",
] as const;

export type Quality = (typeof QUALITIES)[number];

export const profiles = [
  {
    id: 1,
    name: "John Doe",
    sex: "Male",
    qualities: [
      "Tall",
      "Confident",
      "Reliable",
      "Smart",
      "Strong",
      "Adaptable",
      "Agile",
      "Analytical",
      "Assertive",
      "Brave",
    ],
  },
  {
    id: 2,
    name: "Mary Jane",
    sex: "Female",
    qualities: [
      "Pretty",
      "Strong",
      "Kind",
      "Creative",
      "Brave",
      "Confident",
      "Focused",
      "Hardworking",
      "Ingenious",
      "Innovative",
    ],
  },
  {
    id: 3,
    name: "Peter Parker",
    sex: "Male",
    qualities: [
      "Smart",
      "Agile",
      "Resourceful",
      "Adaptable",
      "Logical",
      "Intelligent",
      "Kind",
      "Optimistic",
      "Persistent",
      "Pretty",
    ],
  },
  {
    id: 4,
    name: "Gwen Stacy",
    sex: "Female",
    qualities: [
      "Intelligent",
      "Brave",
      "Analytical",
      "Focused",
      "Visionary",
      "Reliable",
      "Resourceful",
      "Smart",
      "Strong",
      "Tall",
    ],
  },
  {
    id: 5,
    name: "Miles Morales",
    sex: "Male",
    qualities: [
      "Resourceful",
      "Adaptable",
      "Persistent",
      "Optimistic",
      "Ingenious",
      "Assertive",
      "Brave",
      "Confident",
      "Creative",
      "Focused",
    ],
  },
  {
    id: 6,
    name: "Alice Smith",
    sex: "Female",
    qualities: [
      "Creative",
      "Kind",
      "Pretty",
      "Reliable",
      "Hardworking",
      "Ingenious",
      "Innovative",
      "Intelligent",
      "Kind",
      "Logical",
    ],
  },
  {
    id: 7,
    name: "Bob Johnson",
    sex: "Male",
    qualities: [
      "Reliable",
      "Hardworking",
      "Focused",
      "Confident",
      "Assertive",
      "Optimistic",
      "Persistent",
      "Pretty",
      "Reliable",
      "Resourceful",
    ],
  },
  {
    id: 8,
    name: "Charlie Brown",
    sex: "Male",
    qualities: [
      "Persistent",
      "Optimistic",
      "Kind",
      "Adaptable",
      "Agile",
      "Smart",
      "Strong",
      "Tall",
      "Visionary",
      "Adaptable",
    ],
  },
  {
    id: 9,
    name: "Lucy Van Pelt",
    sex: "Female",
    qualities: [
      "Assertive",
      "Intelligent",
      "Logical",
      "Analytical",
      "Brave",
      "Confident",
      "Creative",
      "Focused",
      "Hardworking",
      "Ingenious",
    ],
  },
  {
    id: 10,
    name: "Linus Torvalds",
    sex: "Male",
    qualities: [
      "Innovative",
      "Focused",
      "Ingenious",
      "Logical",
      "Smart",
      "Agile",
      "Resourceful",
      "Adaptable",
      "Persistent",
      "Optimistic",
    ],
  },
  {
    id: 11,
    name: "Ada Lovelace",
    sex: "Female",
    qualities: [
      "Analytical",
      "Visionary",
      "Innovative",
      "Intelligent",
      "Creative",
      "Kind",
      "Pretty",
      "Reliable",
      "Hardworking",
      "Focused",
    ],
  },
  {
    id: 12,
    name: "Alan Turing",
    sex: "Male",
    qualities: [
      "Ingenious",
      "Logical",
      "Analytical",
      "Smart",
      "Innovative",
      "Brave",
      "Confident",
      "Creative",
      "Focused",
      "Hardworking",
    ],
  },
];

export const profileSchema = z.object({
  name: z.string().min(1),
  sex: z.string().min(1),
  qualities: z.array(z.enum(QUALITIES)),
});
